### ISSUE TITLE
cephRBDVolumeDriver does not implement "github.com/docker/go-plugins-helpers/volume".Driver

### ISSUE THREAD

**Issue by linfan** [yp-engineering/rbd-docker-plugin#28]
I tried to get the latest version of rbd-docker-plugin, but got this error:

Golang version: v1.6.0

```
$ go get github.com/yp-engineering/rbd-docker-plugin
# github.com/yp-engineering/rbd-docker-plugin
src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type "github.com/docker/go-plugins-helpers/volume".Driver in argument to "github.com/docker/go-plugins-helpers/volume".NewHandler:
        cephRBDVolumeDriver does not implement "github.com/docker/go-plugins-helpers/volume".Driver (missing Get method)
```

**Comment by phamthanhnhan14** [comment]
Hi All,
I got the same with go 1.6
go version
`go version go1.6 linux/amd64`
go get github.com/yp-engineering/rbd-docker-plugin

```
# github.com/yp-engineering/rbd-docker-plugin
src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type "github.com/docker/go-plugins-helpers/volume".Driver in argument to "github.com/docker/go-plugins-helpers/volume".NewHandler:
    cephRBDVolumeDriver does not implement "github.com/docker/go-plugins-helpers/volume".Driver (missing Get method)
```

Please give me a check.
Thanks,

**Comment by BastienM** [comment]
Hi there,

Got the same problem with go 1.5.1.

``` bash
$ go get github.com/yp-engineering/rbd-docker-plugin

# github.com/yp-engineering/rbd-docker-plugin
go/src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type "github.com/docker/go-plugins-helpers/volume".Driver in argument to "github.com/docker/go-plugins-helpers/volume".NewHandler:
    cephRBDVolumeDriver does not implement "github.com/docker/go-plugins-helpers/volume".Driver (missing Get method)
```

go version: 

``` bash
$ go version
go version go1.5.1 linux/amd64
```

**Comment by somejfn** [comment]
Same issue with the provided Dockerfile:

Step 11 : RUN go get -t .
 ---> Running in e714bfd26338

# github.com/yp-engineering/rbd-docker-plugin

./main.go:83: cannot use d (type cephRBDVolumeDriver) as type "github.com/docker/go-plugins-helpers/volume".Driver in argument to "github.com/docker/go-plugins-helpers/volume".NewHa:
    cephRBDVolumeDriver does not implement "github.com/docker/go-plugins-helpers/volume".Driver (missing Get method)
The command '/bin/sh -c go get -t .' returned a non-zero code: 2

**Comment by dvusboy** [comment]
See #23 and #21. It's been in the backlog for some time. The team's focusing on some Mesos framework. The bottom-line is: this plugin will not work with Docker 1.10 or newer. It has nothing to do with the version of Go.

**Comment by hekaldama** [comment]
Should be working now with latest merged in PR. Let us know if you are not working.

**Comment by nagavenkatab** [comment]
getting same issue

# github.com/yp-engineering/rbd-docker-plugin

/root/src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type volume.Driver in argument to volume.NewHandler:
        cephRBDVolumeDriver does not implement volume.Driver (missing Capabilities method)
root@nagajewel:/home/naga# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
root@nagajewel:/home/naga#
